all:
  children:
    ios_devices:
      children:

        management:
          hosts:
            mgmt-1:
              ansible_host: mgmt-1.lab.local
            mgmt-2:
              ansible_host: mgmt-2.lab.local

        access:
          hosts:
            access-1:
              ansible_host: access-1.lab.local
            access-2:
              ansible_host: access-2.lab.local

        distribution:
          hosts:
            dist-1:
              ansible_host: dist-1.lab.local
            dist-2:
              ansible_host: dist-2.lab.local

        core:
          hosts:
            core-1:
              ansible_host: core-1.lab.local
            core-2:
              ansible_host: core-2.lab.local

    firewall:
      hosts:
        fw-1:
          ansible_host: fw-1.lab.local
