all:
  children:
    ios_devices:
      children:

        management:
          hosts:
            mgmt-1:
              ansible_host: 10.0.30.21
            mgmt-2:
              ansible_host: 10.0.30.22

        access:
          hosts:
            access-1:
              ansible_host: 10.0.30.11
            access-2:
              ansible_host: 10.0.30.12

        distribution:
          hosts:
            dist-1:
              ansible_host: 10.0.30.1
            dist-2:
              ansible_host: 10.0.30.2

        core:
          hosts:
            core-1:
              ansible_host: 10.0.30.101
            core-2:
              ansible_host: 10.0.30.102

    firewall:
      hosts:
        fw-1:
          ansible_host: 10.0.30.201

